### ISSUE TITLE
Add PWA with offline support

### ISSUE THREAD

**Issue by Aniket762** [Aniket762/mergify-masters#10]
A progressive web application is a type of application software delivered through the web, built using common web technologies including HTML, CSS, and JavaScript. It is intended to work on any platform that uses a standards-compliant browser, including both desktop and mobile devices. Progressive Web Apps (PWAs) allow developers to deliver an app-like experience to the user.

If you have any doubts let me know.

**Comment by sumana2001** [comment]
Interested! Please assign it to me
